### ISSUE TITLE
Figure out a way to retrieve definitions from Dictionary.com elegantly.

### ISSUE THREAD

**Issue by DrewDalmedo** [DrewDalmedo/evokab#2]
Refer to testscr.py as a reference.

The current output of the collective definitions of a term is excessively messy. Grappling with this and finding an elegant solution is priority #1, as it makes up a majority of the program's core logic.

**Comment by DrewDalmedo** [comment]
Hello @c-shekhar 
You're more than welcome to contribute to this project, and I would greatly appreciate you starting with this issue. I'm at work right now so I won't be able to add you as a contributor until a little bit later in the day, but feel free to begin working on a solution whenever you'd like!

**Comment by c-shekhar** [comment]
Great, I am on it!
